services:
  - type: web
    name: ollama-server
    env: docker
    plan: starter  # or 'free' if you're on the free tier
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/tags
    ports:
      - port: 80
