services:
  - type: web
    name: ollama-server
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    healthCheckPath: /api/tags
    ports:
      - 11434
